[phases.setup]
nixPkgs = ["nodejs_20", "pnpm-10_x"]

[phases.install]
cmds = ["pnpm install --frozen-lockfile"]

[phases.build]
cmds = ["pnpm turbo run build --filter=product-service..."]

[start]
cmd = "pnpm --filter product-service start"